name: "build"

on:
  push:
    tags:
      - '*'

jobs:
  build-resume:
    runs-on: "ubuntu-22.04"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: "actions/checkout@v2"

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install --yes git gh texlive
          TMP="$(mktemp -d)"
          gh release download "2.18" --repo "jgm/pandoc" --pattern "pandoc-2.18-1-amd64.deb"  --dir "$TMP"
          apt-get install "$TMP/pandoc-2.18-1-amd64.deb"
          rm -r "$TMP"

      - name: "Build document"
        run: |
          . ./env.sh
          thesis_pdf
          thesis_html
          thesis_epub
          mv ./build/* .
          ls --almost-all --recursive --ignore=.git

      - name: "Create and push new orphan branch"
        env:
          NAME: "jaantollander"
          EMAIL: "jaantollander@users.noreply.github.com"
          BRANCH: "build"
        # https://stackoverflow.com/a/58393457
        run: |
          git config --local user.name "$NAME"
          git config --local user.email "$EMAIL"
          git checkout --orphan "$BRANCH"
          git rm -rf .
          git add .
          git commit -m "gh-actions"
          git push origin "$BRANCH" -f
          ls --almost-all --recursive --ignore=.git
