name: "build"

on:
  push:
    tags:
      - '*'

jobs:
  build-resume:
    runs-on: "ubuntu-22.04"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: "actions/checkout@v2"

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install --yes git curl texlive texlive-latex-base texlive-latex-extra texlive-lang-european librsvg2-bin
          TMP="$(mktemp -d)"
          curl --location https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb --output "$TMP/pandoc.deb"
          sudo apt-get install "$TMP/pandoc.deb"

      - name: "Build"
        env:
          NAME: "jaantollander"
          EMAIL: "jaantollander@users.noreply.github.com"
        # https://stackoverflow.com/a/58393457
        run: |
          git config --local user.name "$NAME"
          git config --local user.email "$EMAIL"
          ./thesis build
