name: "build"

on:
  push:
    tags:
      - '*'

jobs:
  build-thesis:
    runs-on: "ubuntu-22.04"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: "actions/checkout@v2"

      - name: "Install dependencies"
        run: |
          ./thesis apt-install

      - name: "Build"
        env:
          NAME: "jaantollander"
          EMAIL: "jaantollander@users.noreply.github.com"
        # https://stackoverflow.com/a/58393457
        run: |
          git config --local user.name "$NAME"
          git config --local user.email "$EMAIL"
          ./thesis build
